version: "3"

services:
  hansel:
    container_name: bitcoincore
    hostname: bitcoincore
    image: massmux/bitcoincore:v0.21.0
    environment:
      - BX_CONFIG=/opt/nodeworkdir/bx.cfg
    volumes:
      - ${PWD}/bitcoinnode:/data/.bitcoin
      - ${PWD}/nodeworkdir:/opt/nodeworkdir
    working_dir: /opt/nodeworkdir
    ports:
      - 18443:18443
      - 18444:18444

